### PR TITLE
fix: flash message not being cleared when using custom session

### LINKED ISSUE #24: Toast messages not being cleared when using custom session
When using custom session, the toast message is not getting cleared from the right session, causing the toast to be shown again if the page is refreshed.

Here is a repo with a reproducible example: https://github.com/michelmattos/remix-toast-with-custom-session

Instructions:
- Run `npm i && npm run dev`
- Click the "send toast" button
- Refresh the page

What to expect?
- Toast not to be shown again after page refresh

What is happening?
- Toast being shown twice after page refresh

### PR DESCRIPTION
**Pull request by michelmattos**
# Description

When using custom session, the toast message is not being cleared from the right session in `getToast`. This is causing the toast message in the UI to be displayed after every page refresh.
This PR fixes it by checking which session to use in a similar way as in `flashMessage`.

Fixes #24 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

A reproducible repo was created to demonstrate the issue: https://github.com/michelmattos/remix-toast-with-custom-session

- [ ] Unit tests

# Checklist:

- [x] My code follows the guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -122,11 +116,13 @@ export async function getToast(
...
 ): Promise<{ toast: ToastMessage | undefined; headers: Headers }> {
-  const session = await getSessionFromRequest(request, customSession);
+  const sessionToUse = customSession ? customSession : sessionStorage;
+  const cookie = request.headers.get("Cookie");
+  const session = await sessionToUse.getSession(cookie);
   const result = flashSessionValuesSchema.safeParse(session.get(FLASH_SESSION));
   const flash = result.success ? result.data : undefined;
   const headers = new Headers({
-    "Set-Cookie": await sessionStorage.commitSession(session),
+    "Set-Cookie": await sessionToUse.commitSession(session),
```
Comment (AlemTuzlak) [inline src/index.ts:125]: ahh nice catch here.

**Review by AlemTuzlak — APPROVED** [review]
